/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import java.util.Scanner;

public class Helicon {

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);

        int n = scan.nextInt();
        int[] a = new int[n];
        for (int i = 0; i < n; i++) {
            a[i] = scan.nextInt();
        }

        long maxSum = Long.MIN_VALUE;

        for (int k = 1; k <= n / 2; k++) {

            for (int start = 0; start < k; start++) {
                long currentMax = 0;
                long runningSum = 0;
                boolean hasElement = false;
                
                for (int i = start; i < n; i += k) {
                    runningSum += a[i];
                    if (runningSum > currentMax) currentMax = runningSum;
                    if (runningSum < 0) runningSum = 0;

                    // Caso todos os números sejam negativos
                    if (a[i] > maxSum) maxSum = a[i];
                    hasElement = true;
                }

                if (hasElement && currentMax > maxSum) {
                    maxSum = currentMax;
                }
            }
        }

        System.out.println(maxSum);
        scan.close();
    }
}
