/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import org.junit.Test;
import static org.junit.Assert.*;

public class HeliconTest {
    @Test public void appHasAGreeting() {
        Helicon classUnderTest = new Helicon();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
